---

- name: Include RedHat specific plays
  include: install-{{ ansible_os_family }}.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian specific plays
  include: install-{{ ansible_os_family }}.yml
  when: ansible_os_family == "Debian"

- name: Copy script for getting JDK tarball 
  template:
    src: get-jdk-latest.sh.j2
    dest: "{{ java_dl_script_path }}/get-jdk-latest.sh"
    owner: root
    group: root
    mode: 0750

- name: Ensure if java home directory exists
  file:
    path: "{{ java_home }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Run get-jdk-latest.sh script
  shell: "{{ java_dl_script_path }}/get-jdk-latest.sh"
  args:
    chdir: "{{ java_home }}"
    creates: /srv/app/var_jdk_script_st

- name: Symlinking JDK to the specified path
  file:
    src: "{{ java_home }}"
    dest: "{{ java_symlink }}"
    owner: root
    group: root
    mode: 0644
    state: link

- name: Environment setup 
  template:
    src: java-home.sh.j2
    dest: /etc/profile.d/java.sh
    mode: 0644
  when: java_home is defined
